# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctd.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tctd.proto\x12\x05spear\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n\tCtdSensor\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x14\n\x0c\x63onductivity\x18\x03 \x01(\x02\x12\x10\n\x08salinity\x18\x04 \x01(\x02\x12\r\n\x05\x64\x65pth\x18\x05 \x01(\x01\x12\x12\n\nsoundspeed\x18\x06 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ctd_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CTDSENSOR._serialized_start=54
  _CTDSENSOR._serialized_end=204
# @@protoc_insertion_point(module_scope)
