sensors:
  ctd_temp:
    thresholds:
      min_temp_c: -6.0
      max_temp_c: 45.0
      max_age_sec: 60.0
      max_step_c: 2.0
  
  bno_attitude:
    thresholds:
      max_age_sec: 90.0
      min_accept_rate: 0.6
      max_range_deg: 15.0
      max_dps: 100.0

  acoustic_acsense_and_beamformer:
    thresholds:
      max_age_sec: 90.0
      target_sps: 52000.0
      sps_tolerance: 0.02
      min_total_samples: 10.0
      min_sample_accept_pct: 99.0
      min_total_chunks: 10.0
      min_chunk_accept_pct: 99.0